chore: Switch to yarn from npm
As of vsce 2.22.0, executing vsce package subcommand without specifying `--yarn` against a project using workspace oddly fails with message like below:

    Error: invalid relative path: extension/../../.git/config

It seems that this error is related with symlinks created by the workspace feature but I don't know and want to investigate the detail. To avoid this error, I needed to use `--yarn` option hence I needed to switch the packaging tool from npm to yarn. It also required me to update statements invoking node scripts too.